/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CircularSlider {
        "bgColor": string;
        "fgColor": string;
        "fontSize": number;
        "max": number;
        "min": number;
        "size": number;
        "textColor": string;
        "thumbColor": string;
        "thumbSize": number;
        "value": number;
    }
}
declare global {
    interface HTMLCircularSliderElement extends Components.CircularSlider, HTMLStencilElement {
    }
    var HTMLCircularSliderElement: {
        prototype: HTMLCircularSliderElement;
        new (): HTMLCircularSliderElement;
    };
    interface HTMLElementTagNameMap {
        "circular-slider": HTMLCircularSliderElement;
    }
}
declare namespace LocalJSX {
    interface CircularSlider {
        "bgColor"?: string;
        "fgColor"?: string;
        "fontSize"?: number;
        "max"?: number;
        "min"?: number;
        "size"?: number;
        "textColor"?: string;
        "thumbColor"?: string;
        "thumbSize"?: number;
        "value"?: number;
    }
    interface IntrinsicElements {
        "circular-slider": CircularSlider;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "circular-slider": LocalJSX.CircularSlider & JSXBase.HTMLAttributes<HTMLCircularSliderElement>;
        }
    }
}
